name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - staging
          - production
        description: target env

jobs:
  build:
    uses: ./.github/workflows/common-build.yml
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Deploying to ${{ inputs.env }}